SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# ASTEROIDS
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 2  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_VERTICES = 12
ASTEROID_LUMPINESS = 0.2

# PLAYER
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_COOLDOWN = 0.3
PLAYER_LIVES = 3
PLAYER_IMMUNITY_TIMER = 2.0
PLAYER_ACCELERATION = 300
PLAYER_MAX_SPEED = 400 

# Player shots
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500

# WEAPONS
WEAPONS = {
    "single": {
        "cooldown": 0.3,
    },
    "double": {
        "cooldown": 0.5,
    },
    "scatter": {
        "cooldown": 0.7,
    }
}

# POWER-UPS
POWERUP_RADIUS = 15
SHIELD_DURATION = 5.0
POWERUP_SPAWN_RATE = 10.0

# BOMBS
BOMB_RADIUS = 10
BOMB_DURATION = 3.0
BOMB_SHOCKWAVE_SPEED = 400

# EXPLOSIONS
EXPLOSION_PARTICLES = 15
EXPLOSION_SPEED = 100
EXPLOSION_PARTICLE_RADIUS = 2
EXPLOSION_DURATION = 0.5