SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# ASTEROIDS
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# PLAYER
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_COOLDOWN = 0.3
PLAYER_LIVES = 3
PLAYER_IMMUNITY_TIMER = 2.0 

# Player shots
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500

# EXPLOSIONS
EXPLOSION_DURATION = 0.5